#! /bin/bash
awk '{
	if ($2 > 50 && $3 > 50 && $4 > 50)
		print $1 " : Pass";
	else
		print $1 " : Fail";
	}'
	
# $2,$3,$4 are the columns of the scores, if they are higher than 5 in all three of them (done with &&), print first column which is identifier and if they pass or false
